language: python
dist: xenial
os: linux
script:
  - coverage run -m scrapy list
  - coverage run -m scrapy crawl jma -t csv -o jma.csv
  - coverage run -m scrapy crawl jtwc -t csv -o jtwc.csv
after_success:
  - bash <(curl -s https://codecov.io/bash)
